.TH AVG_SHOWFONT "1" "March 2011" "libavg 1.5.4" "User Commands"
.SH NAME
avg_showfont \- font enumeration and preview tool
.SH SYNOPSIS
.B avg_showfont
[\fIfontname\fR] [\fItext\fR]
.SH DESCRIPTION
List available font faces and generate preview of their variants.
.PP
If invoked without arguments, avg_showfont generates a list of font family names and prints them on the console.
Fontconfig is used for font discovery. Fonts are searched for in the system font path and in $PWD/fonts. 
.PP
If \fBfontname\fR is specified, the chosen font is displayed in a window, with one line for
each available variant.
.PP
If supplied, the optional \fBtext\fR argument is used instead of the variant name in the
sample text.
.SH AUTHOR
Ulrich von Zadow <coder@c-base.org>
