.TH AVG_SHOWFONT "1" "March 2011" "libavg 1.5.4" "User Commands"
.SH NAME
avg_showfont \- font enumeration and preview tool
.SH SYNOPSIS
.B avg_showfont
[\fIfontname\fR] [\fItext\fR]
.SH DESCRIPTION
List available font faces and generate preview of their variants
.PP
Without providing arguments, it generates a list of font family names and prints them on the console.
Fontconfig is being used for fonts discovery: without specific customization the search path
is the system's one (including eventual user's path in OSX) plus the $PWD/fonts directory (if
it exists).
.PP
When \fBfontname\fR is specified, the chosen font is rendered on a window, with one sample line for
each available variant.
.PP
The optional \fBtext\fR argument is used instead of the default sample text.
.SH AUTHOR
Ulrich Von Zadow <coder@c-base.org>
