.ad 1 
.nh
.hlm 0
.TH avgrc 5 "13 January 2005" "avg"
.SH NAME
avgrc \- avg configuration file
.SH DESCRIPTION
.I avgrc
contains configuration information for the 
.B avg
player, including display data and font directory information. 
.B avg
looks 
for a system-wide file in 
.I /etc/
and a user-specific file in
.I $HOME.
The file is xml-based. There is an example avgrc.default in the  
avg source directory. The available options are described in the 
.B avg
(1) man page. 

.SH FILES
.PD 0
/etc/avgrc - System-wide configuration file.
.P
$HOME/avgrc - User-specific configuration file.
.PD
.SH SEE ALSO
.B avg
(1)
.SH AUTHORS
Ulrich von Zadow (coder@c-base.org)
