.ad 1 
.nh
.hlm 0
.TH avgrc 5 "20 April 2004" "paintlib"
.SH NAME
avgrc \- avg configuration file
.SH DESCRIPTION
.I avgrc
contains configuration information for the 
.B avg
player, including display data and font directory information. 
.B avg
looks 
for a system-wide file in 
.I /etc/
and a user-specific file in
.I $HOME.
The file is xml-based. Its format is:

.PD 0
  <avgrc>
.P 
    <font
.RB dir=" "fontdir" \*(lq/>
    <display
.RI subsystem=" "OGL|DFB" \*(lq
.IP "" 13 
.RI         fullscreen=" "true|false" \*(lq
.IP "" 13
.RI        bpp=" "16|24" \*(lq/>
.P
  </avgrc>
.PD

fontdir is a directory that contains truetype (ttf) fonts that can be used by
avg. For a description of the display parameters, see the 
.B avg
(1) man page. 

.SH EXAMPLE
This is the default /etc/avgrc installed by the build if none is present yet:

.PD 0
  <avgrc>
.P 
    <font
.RB dir=" "/usr/X11R6/lib/X11/fonts/truetype" \*(lq/>
    <display
.RI subsystem=" "OGL" \*(lq
.IP "" 13 
.RI         fullscreen=" "false" \*(lq
.IP "" 13
.RI        bpp=" "24" \*(lq/>
.P
  </avgrc>
.PD

The default file sets the font directory to the X11 font directory and selects 
the OpenGL display subsystem in windowed mode with 24 bits per pixel.
.SH FILES
.PD 0
/etc/avgrc - System-wide configuration file.
.P
$HOME/avgrc - User-specific configuration file.
.PD
.SH SEE ALSO
.B avg
(1)
.SH AUTHORS
Ulrich von Zadow (coder@c-base.org)
