#! /bin/sh

prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: avg-config [OPTION]

Known values for OPTION are:

  --prefix		show avg installation prefix 
  --includedir 		print include file directory
  --help		display this help and exit
  --version		output version information


EOF
#  --libs		print library linking information
#  --cflags		print pre-processor and compiler flags

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --includedir)
        echo $includedir
        ;;

    --version)
	echo 0.1.0
	exit 0
	;;

    --help)
	usage 0
	;;

#    --cflags)
#       	echo @AVG_CFLAGS@ 
#       	;;
#
#    --libs)
#       	echo @AVG_LIBS@ 
#       	;;
    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
