#!/bin/bash
set -x
set -e

if [[ `uname` = Darwin ]] 
then
    if [[ x"$(which port)" = x"/opt/local/bin/port" ]]
    then
        echo "Macports detected"
        glibtoolize --copy --force
    else
        if [[ "$AVG_MAC_ENV_SET" -ne "1" ]]
        then
            echo Please source mac/avg_env.sh before calling bootstrap.
            exit 5 
        fi
        libtoolize --copy --force
    fi
else
    libtoolize --copy --force
fi
aclocal -I m4
autoheader
automake --foreign --add-missing --copy 
autoconf

