#!/bin/bash
set -x
source ../avgenv.sh
echo "Installing to $1, idls to $MOZ_IDLDIR" 
../mkinstalldirs $1 $2
cp -v --preserve=mode xpshell $1/
cp -v --preserve=mode ../avgenv.sh $1/
chmod 777 ../libavg-config
cp -v --preserve=mode ../libavg-config $1/
cp -v --preserve=mode avg $1/
mkdir -p $2
cp -v avg.js $2/
cp -v *.idl $MOZ_IDLDIR/
cp -v *.xpt $MOZ_COMPONENTSDIR/
cp -v .libs/libavg.so.0.0.0 $MOZ_COMPONENTSDIR/libavg.so
rm -fv $MOZ_IDLDIR/compreg.dat
rm -fv $MOZ_IDLDIR/xpti.dat

