#!/usr/bin/env python
# -*- coding: utf-8 -*-

# libavg - Media Playback Engine.
# Copyright (C) 2016-2021 Ulrich von Zadow
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Current versions can be found at www.libavg.de

from __future__ import print_function

import sys
# Add libavg to path
sys.path.insert(0, '..')

import argparse
import os
import stat
import subprocess

import libavg


def exitOnError(returnCode):
    if returnCode != 0:
        sys.exit(returnCode)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--python', action='store_true',
                        help='Run python unittests only')
    args = parser.parse_args()

    initialWorkingDir = os.getcwd()
    libavgPackagePath = os.path.abspath(os.path.dirname(libavg.__file__))

    if not args.python:
        os.chdir(os.path.join(libavgPackagePath, 'test', 'cpptest'))
        for file_ in os.listdir(os.getcwd()):
            if os.path.isfile(file_):
                cppTest = os.path.abspath(file_)
                ret = subprocess.call(cppTest, shell=True)
                exitOnError(ret)

    os.chdir(os.path.join(libavgPackagePath, 'test'))
    testRunner = os.path.abspath('Test.py')
    ret = subprocess.call(testRunner, shell=True)
    exitOnError(ret)

    os.chdir(initialWorkingDir)

