#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys
# Add libavg to path
sys.path.insert(0, '..')

import argparse
import os
import stat
import subprocess

import libavg


def makeExecutable(file_):
    # Note: Setting the permissions is a hack to add +x bit which is removed by
    # distutils from the original files. Setting this permission only works on
    # *NIX
    st = os.stat(file_)
    os.chmod(file_, st.st_mode | stat.S_IEXEC)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--python', action='store_true',
                        help='Run python unittests only')
    args = parser.parse_args()

    initialWorkingDir = os.getcwd()
    libavgPackagePath = os.path.abspath(os.path.dirname(libavg.__file__))

    if not args.python:
        os.chdir(os.path.join(libavgPackagePath, 'test', 'cpptest'))
        for file_ in os.listdir(os.getcwd()):
            if os.path.isfile(file_):
                cppTest = os.path.abspath(file_)
                makeExecutable(cppTest)
                subprocess.call(cppTest, shell=True)

    os.chdir(os.path.join(libavgPackagePath, 'test'))
    testRunner = os.path.abspath('Test.py')
    makeExecutable(testRunner)
    subprocess.call(testRunner, shell=True)

    os.chdir(initialWorkingDir)

