//=============================================================================
//
// Original code Copyright (C) 2003, ART+COM AG Berlin
//
// Released under LGPL.
//
//=============================================================================
//
//   $RCSfile$
//   $Author$
//   $Revision$
//   $Date$
//
//=============================================================================

#include "nsISupports.idl"

[scriptable, uuid(b710b6ec-b816-4947-9216-b67c119af686)]
interface acIJSContextPublisher : nsISupports {
    // Returns a JSContext *, not a long.
    long getContext();
    void setContext(in long theContext);
};

