#!/bin/bash
source avgenv.sh
export __GL_SYNC_TO_VBLANK=1
export __GL_FSAA_MODE=5
JS_SCRIPTNAME=$1
AVG_DEBUG=false
if [[ "$1" == "" ]]
then
  echo "Usage:"
  echo "  avg scriptfile.js [--display=SDL|DFB|OGL] [--bpp=15|16|24|32]"
  echo "                    [--fullscreen=true|false] [--debug]"
  echo 
  echo "For full documentation, see man avg(1)."
  exit 1
fi
for arg in "$2" "$3" "$4" "$5"
do
  cmd=`expr "$arg" : '\(--[a-zA-Z0-9]*\)'`
  val=`expr "$arg" : '.*\=\([a-zA-Z0-9]*\)'`
  case "$cmd" in
    "--display")
      export AVG_DISPLAY=$val
      ;;  
    "--bpp")
      export AVG_BPP=$val
      ;;
    "--fullscreen")
      export AVG_FULLSCREEN=$val
      ;;
    "--debug")
      AVG_DEBUG=true
      ;;
    "")
      ;;
    *)
      echo "  avg scriptfile.js [--display=SDL|DFB|OGL] [--bpp=15|16|24|32]"
      echo "                    [--fullscreen=true|false] [--debug]"
      echo 
      echo "For full documentation, see man avg(1)."
      exit 1
  esac
done
if [[ "$AVG_DEBUG" == "true" ]]
then
    gdb --args xpshell $1
else
    xpshell $1
fi

