//
// $Id$
//

#include "nsISupports.idl"
#include "IJSEvalKruecke.idl"
#include "IAVGEvent.idl"

[scriptable, uuid(e3890769-a960-43ec-bc4f-ded28ef99103)]
interface IAVGPlayer : nsISupports
{
    boolean loadFile(in string fileName);
    void play();
    void stop();

    IAVGNode getElementByID(in string id);
    IAVGNode getRootNode();

    long setInterval(in long time, in string code);
    long setTimeout(in long time, in string code);
    boolean clearInterval(in long id);

    IAVGEvent getCurEvent();
    void setEventDebugLevel(in long level);
    string getErrStr();
    long getErrCode();
};

