//
// $Id$
//

#include "nsISupports.idl"

/**
 * Interface to one or more conrad relais card connected to a serial 
 * port. Per card, up to eight 220V devices can be turned on or off.
 */
[scriptable, uuid(596d7936-745c-47cc-93a3-1078ac704888)]
interface IAVGConradRelais : nsISupports
{
    /**
     * Returns the number of cards connected to the serial port.
     */
    short getNumCards();
    /**
     * Sets or resets one of the relais. index selects the relais
     * to set.
     */
    void set(in short card, in short index, in boolean bOn);
    /**
     * Returns the state of one of the relais. index selects the 
     * relais to query.
     */
    boolean get(in short card, in short index);
};

