//
// $Id$
//

#include "nsISupports.idl"

/**
 * Interface for panorama images. The images need to be generated for 
 * cylindrical projection.
 *
 * All videos also have the attributes supported by IAVGNode and IAVGVideoBase.
 */
[scriptable, uuid(faf59a03-327c-4ac2-80a1-1b61d6bc5896)]
interface IAVGPanoImage : nsISupports
{
    /**
     * The angle of the image. 0 is the left border, getMaxRotation() returns
     * the right border.
     */
    attribute double rotation;

    /**
     * The focal length of the lens used. read-write to allow for easy
     * tests in case the original lens is not known.
     */
    attribute double focallength;

    /**
     * The maximum angle that the image can be rotated to.
     */
    double getMaxRotation();
  
};

