//
// $Id$
//

#include "nsISupports.idl"

[scriptable, uuid(ae073a0f-4b79-414a-9b2e-6a1c133aef2d)]
interface IAVGWindowEvent : nsISupports
{
    const long KEY_UP = 1;
    const long KEY_DOWN = 2;
    const long MOUSE_MOTION = 3;
    const long MOUSE_BUTTON_UP = 4;
    const long MOUSE_BUTTON_DOWN = 5;
    const long MOUSE_OVER = 6;
    const long MOUSE_OUT = 7;
    const long RESIZE = 8;
    const long QUIT = 9;

    readonly attribute boolean fullscreen;
    readonly attribute long width;
    readonly attribute long height;
};

