//
// $Id$
//

#include "nsISupports.idl"

[scriptable, uuid(9f3d4274-e764-4545-8e96-259a70c38166)]
interface IAVGVideo : nsISupports
{
    void play();
    void stop();
    void pause();
    long getNumFrames();
    long getCurFrame();
    void seekToFrame(in long num);
    long getFPS();
   
};

