//
// $Id$
//

#include "nsISupports.idl"

/**
 * This is an interface for generic event data. IAVGPlayer::getCurEvent() 
 * returns a pointer to the currently active event, if there is one.
 * Depending on the type of the event, it will hold additional data
 * described in IAVGMouseEvent, IAVGKeyEvent or IAVGWindowEvent.
 */
[scriptable, uuid(5f06238c-96ca-4bdc-8ea8-763c0ebfc82b)]
interface IAVGEvent : nsISupports
{
    const long KEY_UP = 1;
    const long KEY_DOWN = 2;
    const long MOUSE_MOTION = 3;
    const long MOUSE_BUTTON_UP = 4;
    const long MOUSE_BUTTON_DOWN = 5;
    const long MOUSE_OVER = 6;
    const long MOUSE_OUT = 7;
    const long RESIZE = 8;
    const long QUIT = 9;

    /**
     * Returns the time (in milliseconds since 1970) at which the event happened.
     */
    readonly attribute long when;
    /**
     * One of the constants KEY_UP, KEY_DOWN, MOUSE_MOTION, MOUSE_BUTTON_UP,
     * MOUSE_BUTTON_DOWN, MOUSE_OVER, MOUSE_OUT, RESIZE or QUIT.
     */
    readonly attribute long type;
};

