//
// $Id$
//

#include "nsISupports.idl"

/**
 * Videorecorder-like interface to videos. All video formats and codecs
 * supported by
 * ffmpeg (http://ffmpeg.sourceforge.net/ffmpeg-doc.html#SEC16) are supported
 * by libavg.
 *
 * All videos also have the attributes supported by IAVGNode and IAVGVideoBase.
 */
[scriptable, uuid(9f3d4274-e764-4545-8e96-259a70c38166)]
interface IAVGVideo : nsISupports
{
    /**
     * Returns number of images in the video.
     */
    long getNumFrames();
    /**
     * Returns the current playback image.
     */
    long getCurFrame();
    /**
     * Moves the playback pointer to a new frame. Currently, this is extremely
     * slow because it essentially decodes all frames needed to get to the
     * frame given, starting either from frame 0 or from the current frame.
     */
    void seekToFrame(in long num);
   
};

