//
// $Id$
//

#include "nsISupports.idl"

/**
 * Interface to firewire cameras using libdc1394. 
 *
 * All cameras also have the attributes supported by IAVGNode and IAVGVideoBase.
 */
[scriptable, uuid(9bdb69b4-8808-4dd3-8e28-aaf2aeb12187)]
interface IAVGCamera : nsISupports
{
};

