//
// $Id$
//

#include "nsISupports.idl"
#include "IAVGEvent.idl"

[scriptable, uuid(e3890769-a960-43ec-bc4f-ded28ef99103)]
interface IAVGPlayer : nsISupports
{
    boolean loadFile(in string fileName);
    void play(in float framerate);
    void stop();

    IAVGNode getElementByID(in string id);
    IAVGNode getRootNode();

    long setInterval(in long time, in string code);
    long setTimeout(in long time, in string code);
    boolean clearInterval(in long id);

    IAVGEvent getCurEvent();

    const long DEBUG_NONE=0;
    const long DEBUG_BLTS=1;
    const long DEBUG_PROFILE=2;
    const long DEBUG_MEMORY=4;
    const long DEBUG_EVENTS=8;
    const long DEBUG_EVENTS2=16;
    const long DEBUG_ERROR=32;
    
    void setDebugOutput(in long flags);
    void setDebugOutputFile(in string name);
    string getErrStr();
    long getErrCode();
};

