//
// $Id$
//

#include "nsISupports.idl"

/**
 * An exclusive node is a grouping node that only activates one of its 
 * children. 
 */
[scriptable, uuid(b9823f35-1fd9-4076-9632-f5c65f017c8c)]
interface IAVGExcl : nsISupports
{
    /**
     * Selects which child is active. -1 for none.
     */
    attribute long activeChild;
};

