#!/usr/bin/env python2.6

import sys
#sys.stdout = open("/Users/uzadow/Desktop/postflight.log", "w")
print "Starting postinstall..."
from libavg import avg

print "Building font cache. This can take a while."
Player=avg.Player.get()
print "2"
Player.loadString("""
          <avg width="160" height="120">
            <words x="1" y="1" fontsize="12" font="Bitstream Vera Sans" 
                text="Bitstream Vera Sans" variant="roman"/>
          </avg>
""")
print "Done."
sys.exit(0)
